version: '2'

services:
  postgres:
    image: postgres:13.3
    # restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    # volumes:  ## hardhat node의 경우 매번 초기화(상태 유지 x)가 되기 때문에 DB mount가 필요 없을 듯.
    #   - /usr/local/data/data-postgres:/var/lib/postgresql/data:rw
    ports:
      - 7432:5432

  blockscout:
    depends_on:
      - postgres
    image: blockscout/blockscout:6.0.0
    # restart: always
    container_name: 'blockscout'
    links:
      - postgres:database
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    # env_file:
    #   - ./common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      # BLOCK_TRANSFORMER: 'base' ## base or clique(안됨)
      ETHEREUM_JSONRPC_TRANSPORT: http
      ETHEREUM_JSONRPC_HTTP_URL: http://10.0.2.15:8545/
      ETHEREUM_JSONRPC_TRACE_URL: http://10.0.2.15:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://10.0.2.15:8545/
      DATABASE_URL: postgresql://postgres:@postgres:5432/blockscout?ssl=false
      PORT: 4000
      LOGO: /images/blockscout_logo.svg # home 버튼용
      SHOW_ADDRESS_MARKETCAP_PERCENTAGE: true
      DISABLE_EXCHANGE_RATES: true
      TXS_STATS_ENABLED: true
      ECTO_USE_SSL: false
    ports:
      - 4000:4000
