version: '2'

services:
  validator:
    image: solanalabs/solana:v1.18.26
    restart: always
    # entrypoint: /usr/local/bin/solana-run.sh
    environment:
      - SOLANA_RPC_PORT=8899
      - SOLANA_DATA_DIR=/data/key
      - SOLANA_LEDGER_DIR=/data/ledger
      - SOLANA_FAUCET_KEY=faucet-identity.json
      - SOLANA_VALIDATOR_KEY=validator-identity.json
      - SOLANA_VALIDATOR_VOTE_KEY=validator-vote-account.json
      - SOLANA_VALIDATOR_STATE_KEY=validator-stake-account.json
      # - NDEBUG=profile
    volumes:
      - /app/test-ledger:/data/ledger  # Persist the ledger data
      - /app/test-ledger/config:/usr/bin/config
      - ./key:/data/key
      - ./bin/solana-run.sh:/usr/bin/solana-run.sh
      - ./spl_associated-token-account-1.1.2.so:/usr/local/bin/spl_associated-token-account-1.1.2.so
      - ./spl_feature-proposal-1.0.0.so:/usr/local/bin/spl_feature-proposal-1.0.0.so
      - ./spl_memo-1.0.0.so:/usr/local/bin/spl_memo-1.0.0.so
      - ./spl_memo-3.0.0.so:/usr/local/bin/spl_memo-3.0.0.so
      - ./spl_token-2022-0.9.0.so:/usr/local/bin/spl_token-2022-0.9.0.so
      - ./spl_token-3.5.0.so:/usr/local/bin/spl_token-3.5.0.so
    ports:
      - '8899:8899'
      - '8900:8900'
  explorer:
    image: solana-spe-explorer:latest
    ports:
      - '8080:3000'
